name: workflow

on:
  workflow_dispatch
  #schedule: 
    #- cron: '0 23 * * *' 

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 1200
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Running
      run: |
        echo "Running!"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install datetime
        pip install sodapy
        pip install plotly 
    - name: Run VR_MonthlyDiff_forGithub.py
      env: 
        NYS_APP_TOKEN: ${{secrets.NYS_APP_TOKEN}} 
      run: |
        python ./VR_MonthlyDiff_forGithub.py
    - name: Git push
      run: |
        git config --global user.name "rrlinrr"
        git config --global user.email "45771006+rrlinrr@users.noreply.github.com"
        git add .
        git commit -m "update"
        git push
